# -*- coding: utf-8 -*-
"""Create_Insert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0XoFJRNC3IsUk4T5rJTp3C30T6l8k_v
"""

from google.colab import files
file= files.upload()

import sqlite3
database= "database.sqlite"
conn= sqlite3.connect(database)
print("Opened the database successfully")

conn.execute('''CREATE TABLE Class_new
(SNo INT PRIMARY KEY NOT NULL,
Roll_No INT NOT NULL,
NAME TEXT NOT NULL,
AGE INT DEFAULT(15),
GENDER TEXT NOT NULL,
Email_ID TEXT NOT NULL,
Contact_No INT NOT NULL);''')

conn.execute('''INSERT INTO Class_new(SNo,Roll_No,NAME,AGE,GENDER, Email_ID, Contact_No) \
VALUES(1,1,"Amulya",16, "Male", "abc@gmail.com", 12345);''')

conn.execute('''INSERT INTO Class_new(SNo,Roll_No,NAME,AGE,GENDER, Email_ID, Contact_No) \
VALUES(2,2,"Atulya",15, "Male", "def@gmail.com", 67819);''')

conn.execute('''INSERT INTO Class_new(SNo,Roll_No,NAME,AGE,GENDER, Email_ID, Contact_No) \
VALUES(3,3,"Hi",15, "Female", "xyz@gmail.com", 34598);''')

conn.commit()
print("Record created Successfully")

import pandas as pd

tables= pd.read_sql('''SELECT * FROM sqlite_master WHERE type='table';''',conn)
tables

Class_10= pd.read_sql('''SELECT * FROM Class_new;''',conn)
Class_10