# -*- coding: utf-8 -*-
"""Analyze.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1loTd6PZVlLIrUB4kE0GEJNR1l9MY5FJT
"""

from google.colab import files
file= files.upload()

import sqlite3

database='Analyzing.sqlite'
conn= sqlite3.connect(database)
print("Connection to database was successfull.")

import pandas as pd

tables_data= pd.read_sql("""SELECT * FROM sqlite_master WHERE type='table' ;""", conn)
tables_data

match_data= pd.read_sql("""SELECT * FROM Match ;""", conn)
match_data

match_data.info()

match_data.describe()