# -*- coding: utf-8 -*-
"""Data_Of_Table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMjYTeR4pQtLeDG_RWmU6g7mH-_if6ro
"""

from google.colab import files
file= files.upload()

import sqlite3

database='Analyzing.sqlite'
conn= sqlite3.connect(database)
print("Connection to database was successfull.")

import pandas as pd

tables_data= pd.read_sql("""SELECT * FROM sqlite_master WHERE type='table' ;""", conn)
tables_data

match_data= pd.read_sql("""SELECT * FROM Match ;""", conn)
match_data

match_data_c= pd.read_sql("""SELECT MIN(Win_Margin),MAX(Win_Margin) FROM Match ;""", conn)
match_data_c