# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PgDR8by0HQGoLJGKi5wYEytX8xVjyEY2
"""

from google.colab import files
file= files.upload()

import sqlite3

database= "basketball.sqlite"
conn= sqlite3.connect(database)
print("Opened the data successfully")

import pandas as pd

tables= pd.read_sql("""SELECT * FROM sqlite_master WHERE type='table';""", conn)
tables

tables_2= pd.read_sql("""SELECT * FROM Player;""", conn)
tables_2

tables_3= pd.read_sql("""SELECT * FROM Draft;""", conn)
tables_3

tables_4= pd.read_sql("""SELECT * FROM Team;""", conn)
tables_4

tables_5= pd.read_sql("""SELECT * FROM Player_Salary;""", conn)
tables_5