# -*- coding: utf-8 -*-
"""JOIN_SQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJHK5OAzaxDscoJgZfgiVnKDdhHmm-uL
"""

from google.colab import files
file= files.upload()

import sqlite3
database="database.sqlite"
conn= sqlite3.connect(database)
print("Connection established successfully.")

import pandas as pd
tables= pd.read_sql('''SELECT * FROM sqlite_master WHERE type= 'table';''',conn)
tables

city= pd.read_sql('''SELECT * FROM City;''',conn)
city.head(5)

country= pd.read_sql('''SELECT * FROM Country;''',conn)
country.head(5)

join_inner= pd.read_sql('''SELECT c.Country_Id, c.Country_Name, ci.City_Name
FROM Country c
INNER JOIN City ci
ON c.Country_Id == ci.Country_id;''',conn)

join_inner

Player= pd.read_sql('''SELECT * FROM Player;''',conn)
Player.head(5)

season= pd.read_sql('''SELECT * FROM season;''',conn)
season.head(5)

Outer_Join= pd.read_sql('''SELECT * FROM Player p
LEFT JOIN season s
ON p.Player_Id == s.Man_of_the_Series;''',conn)

Outer_Join.head(5)

cross_join= pd.read_sql('''SELECT c.Country_Id, c.Country_Name, ci.City_Name
FROM Country c
INNER JOIN City ci;''',conn)

cross_join

union_clause= pd.read_sql('''SELECT Player_Name FROM Player UNION Select Team_Name FROM Team;''',conn)

union_clause