# -*- coding: utf-8 -*-
"""Aggregate Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b6YTKyAl-yYO1uxgsepM3Z4lG5MEWr2l
"""

from google.colab import files
file= files.upload()

import sqlite3
database= "Analyzing_2.sqlite"
conn= sqlite3.connect(database)
print("Connection was successfull")

import pandas as pd
tables= pd.read_sql("""SELECT * FROM sqlite_master WHERE type='table' ;""", conn)
tables

match_data= pd.read_sql("""SELECT * FROM Match;""", conn)
match_data.head(3)

result1= pd.read_sql("""SELECT AVG(Win_Margin), Match_Winner FROM MATCH WHERE Season_Id == 9 GROUP BY Match_Winner ORDER BY AVG(Win_Margin) DESC;""", conn)
result1

result2= pd.read_sql("""SELECT DISTINCT(Venue_Id) FROM MATCH WHERE Season_Id == 9""", conn)
result2

result3= pd.read_sql("""SELECT COUNT(DISTINCT(Venue_Id)) FROM MATCH WHERE Season_Id == 9""", conn)
result3

result4= pd.read_sql("""SELECT MIN(Win_Margin),MAX(Win_Margin),AVG(Win_Margin),COUNT(DISTINCT(Man_Of_The_Match)) FROM MATCH""", conn)
result4

result5= pd.read_sql("""SELECT SUM(Win_Margin) FROM MATCH WHERE Season_Id == 9""", conn)
result5